# Generated by Django 6.0.6 on 2026-06-12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_address_payment_method_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="product_title",
            new_name="name",
        ),
    ]
