# Generated by Django 6.0.6 on 2026-06-08 16:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('product_id', models.UUIDField(db_index=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['buyer', 'product_id'], name='favorites_f_buyer_i_e0be36_idx')],
                'constraints': [models.UniqueConstraint(fields=('buyer', 'product_id'), name='unique_buyer_favorite_product')],
            },
        ),
        migrations.CreateModel(
            name='ProductSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('product_id', models.UUIDField(db_index=True)),
                ('notify_on', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['buyer', 'product_id'], name='favorites_p_buyer_i_484697_idx')],
                'constraints': [models.UniqueConstraint(fields=('buyer', 'product_id'), name='unique_buyer_product_subscription')],
            },
        ),
    ]
