# Generated by Django 6.0.6 on 2026-06-08 16:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('ORDER_STATUS_CHANGED', 'Order status changed'), ('BACK_IN_STOCK', 'Back in stock'), ('PRICE_DROP', 'Price drop'), ('PROMO', 'Promo'), ('SYSTEM', 'System')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('payload', models.JSONField(default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['buyer', 'is_read', 'created_at'], name='notificatio_buyer_i_02d4cb_idx'), models.Index(fields=['type'], name='notificatio_type_ea918f_idx')],
            },
        ),
    ]
