# Generated by Django 6.0.6 on 2026-06-08 16:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('session_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('sku_id', models.UUIDField(db_index=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price_at_add', models.PositiveBigIntegerField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('unavailable_reason', models.CharField(blank=True, choices=[('OUT_OF_STOCK', 'Out of stock'), ('PRODUCT_BLOCKED', 'Product blocked'), ('PRODUCT_DELETED', 'Product deleted'), ('PRODUCT_DELISTED', 'Product delisted'), ('ON_MODERATION', 'On moderation')], max_length=50, null=True)),
                ('unavailable_message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'sku_id'], name='carts_carti_user_id_982741_idx'), models.Index(fields=['session_id', 'sku_id'], name='carts_carti_session_4028dc_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('session_id__isnull', True), ('user__isnull', False)), models.Q(('session_id__isnull', False), ('user__isnull', True)), _connector='OR'), name='cart_item_exactly_one_identity'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'sku_id'), name='unique_user_cart_sku'), models.UniqueConstraint(condition=models.Q(('session_id__isnull', False)), fields=('session_id', 'sku_id'), name='unique_session_cart_sku')],
            },
        ),
    ]
